### ISSUE TITLE
Final Review

### ISSUE THREAD

**Issue by jcheon** [ballen2024/ballen2024.github.io#3]
# Summary 

    *Here, place a 1-paragraph summary that outlines (1) what the project investigated, (2) what insights/conclusions they found, and (3) what is the next planned step.* 

This project looked into baseball and how data could predict some aspects of the game. There were 2 predictions that were looked into and they were 
1) how teams run-differential in the first month of the season could predict win-loss percentages 
2) would more homeruns improve win-loss.

Brenden has found great insight as to discussing his first question. He found that run-differentials in the first month had significance into predicting how many win-loss a team would have. Though it was only an R^2 of 0.00015, it still was cool to see that this could impact a teams performance. 

I think a good next plan step is to divide up by each month to predict a team's win-loss. Instead of only analyzing the first month, it would be great to see it by each month, by quarter,  before/after playoffs, etc. Maybe this would provide more insight. 

    # Data Preparation 

    *Here, describe (1) what tables have been developed and what kind of information they hold; (2) answer: does the portfolio demonstrate that it has tidy organization? (3) answer: does the portfolio demonstrate cleaned data?. If any of these answers are NO or could be improved to make it easier for the general public to understand, provide specific guidance on how it could be improved.* 

Various tables were created in order to be able to conclude his analysis. 
1) game data: date, day or night game, date, which park, crowd attendance, duration of game, scores of both teams and homeruns of both teams. 
2) Foul balls: teams, date, hit type, velocity, predicted zone, amera zone, and used zone. 
3) Launch data: date, field, home and away team, velocity, and angle. 
4) Standings: rank, teams, games, win/losses, run differentials. 

These tables do present tidy data except for one column. In the foul_balls table, there is a hit_type column where it is not tidy. I'm sure there are a lot of different type of hits, but maybe it would be a little more tidy. 

Overall, the tables are very clean and with appropriate types. 

    # Modeling 

    *Here, describe (1) what predictive models have been built and what are their (dependent variable) predictors?; (2) answer: does the portfolio accurately describe the purpose of the models? (3) answer: does the portfolio accurately interpret the model's summary?* 

1) Linear model on win/loss percentage as dependent variable and run differentials as independent variables. This was a successful model as run differential had a strong p-value and overall r^2 was 0.4623. That's great! The portfolio does a great job at displaying this result, but could work a little more on explaining like, what exactly run differentials is. 

2) Another linear model was done to predict win/loss percentage (dependent variable) using number of home runs (independent). It was not significant and was explained in the analysis.  

I think there would be more variables that would be explored. Instead of running a linear model on just one variables at a time, it would be nice to see other variables in play. Some examples would be duration of game, home team score / visitor score, or day_night game because who know, these might have some impact on win/loss for teams. 

    # Validation 

    *Here, answer: (1) has a model been cross-validated using testing and training sets? (2) has the accuracy of the cross-validation been explained clearly and appropriately?* 

Yes, the models were using cross-validation testing and training sets. 

    # R Proficiency 

    *Here, describe the strengths and weaknesses of how the R code has been developed; is it easy to read and understand? Have appropriate R techniques been used to make the code easy to maintain and reuse? Have appropriate functional programming techniques been used?* 

Brendan seems to be very strong with R with various libraries were used such as dplyr, regular expression, and understanding what needed to be done to accomplish his task. Though there are a few for loops, but it seemed to be okay as it only iterated through 400 rows. 

    # Communication 

    *Has the portfolio been described in enough detail, but in wording that is easy for anyone to understand? Are visualizations used effectively to help communicate the data? What are its strengths and weaknesses?* 

The portfolio did a great job at explaining what was going on and what he wanted to get across. The visualizations are great and appropriate for his analysis. The strength of this portfolio was the communication for sure as it is structured and organized beautifully. 

    # Critical Thinking 

    *Does the operationalization and social impact demonstrate careful, critical thought about the future of the project? What are possible unintended consequences or variables that the author has not discussed?*

The operationalization and social impact portion does explain what could potentially happen. I do agree that these variables could be used for trades and has little impact on social issues.

**Comment by ballen2024** [comment]
# Data Preparation and Modeling (*19* out of 20%)

*I agree with Jonathan's assessment of this aspect of the portfolio. I ended up not looking at the hit type of my foul balls data, so it slipped my mind to tidy that up. After looking at it, I agree that it was not tidy, and should either be cleaned up or removed.*

# Validation and Operationalization (*19* out of 20%)

*I think Jonathan hit on the points of how I used cross-validation and had good R-squared values. I am not sure why the squared value was addressed as weak in the Summary section but strong in the Modeling section. Maybe I am misunderstanding which he meant to address in each of those. I agree that I could have used more variables to model. I think my discussion surrounding my models efficacy was good as well, which agrees Jonathan's assessment.*


# R Proficiency (*20* out of 20%)

*As Jonathan pointed out, I think I too have a good grasp of R. Jonathan addressed my use of a for-loop (which I also pointed out in my deliverable), but as we both stated, I rationalized its use because it did not include many iterations. I also included some obscure but helpful libraries that were praised by those that reviewed my deliverables, such as lemon and baseballr.*


# Communication (*20* out of 20%)

*I think this was one of the strongest elements of y portfolio. I believe that I did a good job of presenting my findings and structuring my deliverable pages to be clean and readable.*


# Critical Thinking (*20* out of 20%)

*With the topic of sports, there were not really significant social implications to discuss; however, I think I did a god job addressing the operationalization of the model and how I would move forward with additional data collection.*
